export default [
  [
    {
      code: 'IntlBackslash',
      main: { en: '§', ru: '>' },
      shift: { en: '±', ru: '<' },
      isLetter: false,
      element: null,
      className: '',
    },
    {
      code: 'Digit1',
      main: { en: '1', ru: '' },
      shift: { en: '!', ru: '' },
      isLetter: false,
      element: null,
      className: '',
    },
    {
      code: 'Digit',
      main: { en: '2', ru: '' },
      shift: { en: '@', ru: '' },
      isLetter: false,
      element: null,
      className: '',
    },
    {
      code: 'Digit3',
      main: { en: '3', ru: '' },
      shift: { en: '#', ru: '' },
      isLetter: false,
      element: null,
      className: '',
    },
    {
      code: 'Digit4',
      main: { en: '4', ru: '' },
      shift: { en: '$', ru: '' },
      isLetter: false,
      element: null,
      className: '',
    },
    {
      code: 'Digit5',
      main: { en: '5', ru: '' },
      shift: { en: '%', ru: '' },
      isLetter: false,
      element: null,
      className: '',
    },
    {
      code: 'Digit6',
      main: { en: '6', ru: '' },
      shift: { en: '^', ru: '' },
      isLetter: false,
      element: null,
      className: '',
    },
    {
      code: 'Digit7',
      main: { en: '7', ru: '' },
      shift: { en: '&', ru: '' },
      isLetter: false,
      element: null,
      className: '',
    },
    {
      code: 'Digit8',
      main: { en: '8', ru: '' },
      shift: { en: '*', ru: '' },
      isLetter: false,
      element: null,
      className: '',
    },
    {
      code: 'Digit9',
      main: { en: '9', ru: '' },
      shift: { en: '(', ru: '' },
      isLetter: false,
      element: null,
      className: '',
    },
    {
      code: 'Digit0',
      main: { en: '0', ru: '' },
      shift: { en: ')', ru: '' },
      isLetter: false,
      element: null,
      className: '',
    },
    {
      code: 'Minus',
      main: { en: '-', ru: '' },
      shift: { en: '_', ru: '' },
      isLetter: false,
      element: null,
      className: '',
    },
    {
      code: 'Equal',
      main: { en: '=', ru: '' },
      shift: { en: '+', ru: '' },
      isLetter: false,
      element: null,
      className: '',
    },
    {
      code: 'Backspace',
      main: { en: 'Backspace', ru: 'Backspace' },
      shift: { en: 'Backspace', ru: 'Backspace' },
      isLetter: false,
      element: null,
      className: 'two-place',
    },
  ],
  [
    {
      code: 'Tab',
      main: { en: 'Tab', ru: 'Tab' },
      shift: { en: 'Tab', ru: 'Tab' },
      isLetter: false,
      element: null,
      className: 'shift-key',
    },
    {
      code: 'KeyQ',
      main: { en: 'q', ru: '' },
      shift: { en: 'Q', ru: '' },
      isLetter: true,
      element: null,
      className: '',
    },
    {
      code: 'KeyW',
      main: { en: 'w', ru: '' },
      shift: { en: 'W', ru: '' },
      isLetter: true,
      element: null,
      className: '',
    },
    {
      code: 'KeyE',
      main: { en: 'e', ru: '' },
      shift: { en: 'E', ru: '' },
      isLetter: true,
      element: null,
      className: '',
    },
    {
      code: 'KeyR',
      main: { en: 'r', ru: '' },
      shift: { en: 'R', ru: '' },
      isLetter: true,
      element: null,
      className: '',
    },
    {
      code: 'KeyT',
      main: { en: 't', ru: '' },
      shift: { en: 'T', ru: '' },
      isLetter: true,
      element: null,
      className: '',
    },
    {
      code: 'KeyY',
      main: { en: 'y', ru: '' },
      shift: { en: 'Y', ru: '' },
      isLetter: true,
      element: null,
      className: '',
    },
    {
      code: 'KeyU',
      main: { en: 'u', ru: '' },
      shift: { en: 'U', ru: '' },
      isLetter: true,
      element: null,
      className: '',
    },
    {
      code: 'KeyI',
      main: { en: 'i', ru: '' },
      shift: { en: 'I', ru: '' },
      isLetter: true,
      element: null,
      className: '',
    },
    {
      code: 'KeyO',
      main: { en: 'o', ru: '' },
      shift: { en: 'O', ru: '' },
      isLetter: true,
      element: null,
      className: '',
    },
    {
      code: 'KeyP',
      main: { en: 'p', ru: '' },
      shift: { en: 'P', ru: '' },
      isLetter: true,
      element: null,
      className: '',
    },
    {
      code: 'BracketLeft',
      main: { en: '[', ru: '' },
      shift: { en: '{', ru: '' },
      isLetter: false,
      element: null,
      className: '',
    },
    {
      code: 'BracketRight',
      main: { en: ']', ru: '' },
      shift: { en: '}', ru: '' },
      isLetter: false,
      element: null,
      className: '',
    },
    {
      code: 'Backslash',
      main: { en: '\\', ru: '' },
      shift: { en: '|', ru: '' },
      isLetter: false,
      element: null,
      className: '',
    },
    {
      code: 'Delete',
      main: { en: 'Del', ru: 'Del' },
      shift: { en: 'Del', ru: 'Del' },
      isLetter: false,
      element: null,
      className: 'shift-key',
    },
  ],
  [
    {
      code: 'CapsLock',
      main: { en: 'CapsLock', ru: 'CapsLock' },
      shift: { en: 'CapsLock', ru: 'CapsLock' },
      isLetter: false,
      element: null,
      className: 'two-place',
    },
    {
      code: 'KeyA',
      main: { en: 'a', ru: '' },
      shift: { en: 'A', ru: '' },
      isLetter: true,
      element: null,
      className: '',
    },
    {
      code: 'KeyS',
      main: { en: 's', ru: '' },
      shift: { en: 'S', ru: '' },
      isLetter: true,
      element: null,
      className: '',
    },
    {
      code: 'KeyD',
      main: { en: 'd', ru: '' },
      shift: { en: 'D', ru: '' },
      isLetter: true,
      element: null,
      className: '',
    },
    {
      code: 'KeyF',
      main: { en: 'f', ru: '' },
      shift: { en: 'F', ru: '' },
      isLetter: true,
      element: null,
      className: '',
    },
    {
      code: 'KeyG',
      main: { en: 'g', ru: '' },
      shift: { en: 'G', ru: '' },
      isLetter: true,
      element: null,
      className: '',
    },
    {
      code: 'KeyH',
      main: { en: 'h', ru: '' },
      shift: { en: 'H', ru: '' },
      isLetter: true,
      element: null,
      className: '',
    },
    {
      code: 'KeyJ',
      main: { en: 'j', ru: '' },
      shift: { en: 'J', ru: '' },
      isLetter: true,
      element: null,
      className: '',
    },
    {
      code: 'KeyK',
      main: { en: 'k', ru: '' },
      shift: { en: 'K', ru: '' },
      isLetter: true,
      element: null,
      className: '',
    },
    {
      code: 'KeyL',
      main: { en: 'l', ru: '' },
      shift: { en: 'L', ru: '' },
      isLetter: true,
      element: null,
      className: '',
    },
    {
      code: 'Semicolon',
      main: { en: ';', ru: '' },
      shift: { en: ':', ru: '' },
      isLetter: false,
      element: null,
      className: '',
    },
    {
      code: 'Quote',
      main: { en: '\'', ru: '' },
      shift: { en: '"', ru: '' },
      isLetter: false,
      element: null,
      className: '',
    },
    {
      code: 'Enter',
      main: { en: 'Enter', ru: 'Enter' },
      shift: { en: 'Enter', ru: 'Enter' },
      isLetter: false,
      element: null,
      className: 'two-place',
    },
  ],
  [
    {
      code: 'ShiftLeft',
      main: { en: 'Shift', ru: 'Shift' },
      shift: { en: 'Shift', ru: 'Shift' },
      isLetter: false,
      element: null,
      className: 'shift-key',
    },
    {
      code: 'Backquote',
      main: { en: '`', ru: '' },
      shift: { en: '~', ru: '' },
      isLetter: false,
      element: null,
      className: '',
    },
    {
      code: 'KeyZ',
      main: { en: 'z', ru: '' },
      shift: { en: 'Z', ru: '' },
      isLetter: true,
      element: null,
      className: '',
    },
    {
      code: 'KeyX',
      main: { en: 'x', ru: '' },
      shift: { en: 'X', ru: '' },
      isLetter: true,
      element: null,
      className: '',
    },
    {
      code: 'KeyC',
      main: { en: 'c', ru: '' },
      shift: { en: 'C', ru: '' },
      isLetter: true,
      element: null,
      className: '',
    },
    {
      code: 'KeyV',
      main: { en: 'v', ru: '' },
      shift: { en: 'V', ru: '' },
      isLetter: true,
      element: null,
      className: '',
    },
    {
      code: 'KeyB',
      main: { en: 'b', ru: '' },
      shift: { en: 'B', ru: '' },
      isLetter: true,
      element: null,
      className: '',
    },
    {
      code: 'KeyN',
      main: { en: 'n', ru: '' },
      shift: { en: 'N', ru: '' },
      isLetter: true,
      element: null,
      className: '',
    },
    {
      code: 'KeyM',
      main: { en: 'm', ru: '' },
      shift: { en: 'M', ru: '' },
      isLetter: true,
      element: null,
      className: '',
    },
    {
      code: 'Comma',
      main: { en: ',', ru: '' },
      shift: { en: '<', ru: '' },
      isLetter: false,
      element: null,
      className: '',
    },
    {
      code: 'Period',
      main: { en: '.', ru: '' },
      shift: { en: '>', ru: '' },
      isLetter: false,
      element: null,
      className: '',
    },
    {
      code: 'Slash',
      main: { en: '/', ru: '' },
      shift: { en: '?', ru: '' },
      isLetter: false,
      element: null,
      className: '',
    },
    {
      code: 'ArrowUp',
      main: { en: '&uarr;', ru: '&uarr;' },
      shift: { en: '&uarr;', ru: '&uarr;' },
      isLetter: false,
      element: null,
      className: 'arrow-key',
    },
    {
      code: 'ShiftRight',
      main: { en: 'Shift', ru: 'Shift' },
      shift: { en: 'Shift', ru: 'Shift' },
      isLetter: false,
      element: null,
      className: 'shift-key',
    },
  ],
  [
    {
      code: 'ControlLeft',
      main: { en: 'Control', ru: 'Control' },
      shift: { en: 'Control', ru: 'Control' },
      isLetter: false,
      element: null,
      className: '',
    },
    {
      code: 'AltLeft',
      main: { en: 'Opt', ru: 'Opt' },
      shift: { en: 'Opt', ru: 'Opt' },
      isLetter: false,
      element: null,
      className: '',
    },
    {
      code: 'OSLeft',
      main: { en: 'Cmd', ru: 'Cmd' },
      shift: { en: 'Cmd', ru: 'Cmd' },
      isLetter: false,
      element: null,
      className: '',
    },
    {
      code: 'Space',
      main: { en: 'Space', ru: 'Space' },
      shift: { en: 'Space', ru: 'Space' },
      isLetter: false,
      element: null,
      className: 'five-place',
    },
    {
      code: 'OSRight',
      main: { en: 'Cmd', ru: 'Cmd' },
      shift: { en: 'Cmd', ru: 'Cmd' },
      isLetter: false,
      element: null,
      className: '',
    },
    {
      code: 'AltRight',
      main: { en: 'Opt', ru: 'Opt' },
      shift: { en: 'Opt', ru: 'Opt' },
      isLetter: false,
      element: null,
      className: '',
    },
    {
      code: 'ArrowLeft',
      main: { en: '&larr;', ru: '&larr;' },
      shift: { en: '&larr;', ru: '&larr;' },
      isLetter: false,
      element: null,
      className: 'arrow-key',
    },
    {
      code: 'ArrowDown',
      main: { en: '&darr;', ru: '&darr;' },
      shift: { en: '&darr;', ru: '&darr;' },
      isLetter: false,
      element: null,
      className: 'arrow-key',
    },
    {
      code: 'ArrowRight',
      main: { en: '&rarr;', ru: '&rarr;' },
      shift: { en: '&rarr;', ru: '&rarr;' },
      isLetter: false,
      element: null,
      className: 'arrow-key',
    },
  ],
];
