export default [
  [
    {
      keyCode: 220,
      main: { en: '§', ru: '>' },
      shift: { en: '±', ru: '<' },
      isLetter: false,
      element: null,
      className: '',
    },
    {
      keyCode: 49,
      main: { en: '1', ru: '' },
      shift: { en: '!', ru: '' },
      isLetter: false,
      element: null,
      className: '',
    },
    {
      keyCode: 50,
      main: { en: '2', ru: '' },
      shift: { en: '@', ru: '' },
      isLetter: false,
      element: null,
      className: '',
    },
    {
      keyCode: 51,
      main: { en: '3', ru: '' },
      shift: { en: '#', ru: '' },
      isLetter: false,
      element: null,
      className: '',
    },
    {
      keyCode: 52,
      main: { en: '4', ru: '' },
      shift: { en: '$', ru: '' },
      isLetter: false,
      element: null,
      className: '',
    },
    {
      keyCode: 53,
      main: { en: '5', ru: '' },
      shift: { en: '%', ru: '' },
      isLetter: false,
      element: null,
      className: '',
    },
    {
      keyCode: 54,
      main: { en: '6', ru: '' },
      shift: { en: '^', ru: '' },
      isLetter: false,
      element: null,
      className: '',
    },
    {
      keyCode: 55,
      main: { en: '7', ru: '' },
      shift: { en: '&', ru: '' },
      isLetter: false,
      element: null,
      className: '',
    },
    {
      keyCode: 56,
      main: { en: '8', ru: '' },
      shift: { en: '*', ru: '' },
      isLetter: false,
      element: null,
      className: '',
    },
    {
      keyCode: 57,
      main: { en: '9', ru: '' },
      shift: { en: '(', ru: '' },
      isLetter: false,
      element: null,
      className: '',
    },
    {
      keyCode: 48,
      main: { en: '0', ru: '' },
      shift: { en: ')', ru: '' },
      isLetter: false,
      element: null,
      className: '',
    },
    {
      keyCode: 173,
      main: { en: '-', ru: '' },
      shift: { en: '_', ru: '' },
      isLetter: false,
      element: null,
      className: '',
    },
    {
      keyCode: 61,
      main: { en: '=', ru: '' },
      shift: { en: '+', ru: '' },
      isLetter: false,
      element: null,
      className: '',
    },
    {
      keyCode: 8,
      main: { en: 'Backspace', ru: 'Backspace' },
      shift: { en: 'Backspace', ru: 'Backspace' },
      isLetter: false,
      element: null,
      className: 'two-place',
    },
  ],
  [
    {
      keyCode: 16,
      main: { en: 'Tab', ru: 'Tab' },
      shift: { en: 'Tab', ru: 'Tab' },
      isLetter: false,
      element: null,
      className: 'two-place',
    },
    {
      keyCode: 81,
      main: { en: 'q', ru: '' },
      shift: { en: 'Q', ru: '' },
      isLetter: true,
      element: null,
      className: '',
    },
    {
      keyCode: 87,
      main: { en: 'w', ru: '' },
      shift: { en: 'W', ru: '' },
      isLetter: true,
      element: null,
      className: '',
    },
    {
      keyCode: 69,
      main: { en: 'e', ru: '' },
      shift: { en: 'E', ru: '' },
      isLetter: true,
      element: null,
      className: '',
    },
    {
      keyCode: 82,
      main: { en: 'r', ru: '' },
      shift: { en: 'R', ru: '' },
      isLetter: true,
      element: null,
      className: '',
    },
    {
      keyCode: 84,
      main: { en: 't', ru: '' },
      shift: { en: 'T', ru: '' },
      isLetter: true,
      element: null,
      className: '',
    },
    {
      keyCode: 89,
      main: { en: 'y', ru: '' },
      shift: { en: 'Y', ru: '' },
      isLetter: true,
      element: null,
      className: '',
    },
    {
      keyCode: 85,
      main: { en: 'u', ru: '' },
      shift: { en: 'U', ru: '' },
      isLetter: true,
      element: null,
      className: '',
    },
    {
      keyCode: 73,
      main: { en: 'i', ru: '' },
      shift: { en: 'I', ru: '' },
      isLetter: true,
      element: null,
      className: '',
    },
    {
      keyCode: 79,
      main: { en: 'o', ru: '' },
      shift: { en: 'O', ru: '' },
      isLetter: true,
      element: null,
      className: '',
    },
    {
      keyCode: 80,
      main: { en: 'p', ru: '' },
      shift: { en: 'P', ru: '' },
      isLetter: true,
      element: null,
      className: '',
    },
    {
      keyCode: 219,
      main: { en: '[', ru: '' },
      shift: { en: '{', ru: '' },
      isLetter: false,
      element: null,
      className: '',
    },
    {
      keyCode: 221,
      main: { en: ']', ru: '' },
      shift: { en: '}', ru: '' },
      isLetter: false,
      element: null,
      className: '',
    },
    {
      keyCode: 220,
      main: { en: '\\', ru: '' },
      shift: { en: '|', ru: '' },
      isLetter: false,
      element: null,
      className: '',
    },
  ],
  [
    {
      keyCode: 20,
      main: { en: 'CapsLock', ru: 'CapsLock' },
      shift: { en: 'CapsLock', ru: 'CapsLock' },
      isLetter: false,
      element: null,
      className: 'two-place',
    },
    {
      keyCode: 65,
      main: { en: 'a', ru: '' },
      shift: { en: 'A', ru: '' },
      isLetter: true,
      element: null,
      className: '',
    },
    {
      keyCode: 83,
      main: { en: 's', ru: '' },
      shift: { en: 'S', ru: '' },
      isLetter: true,
      element: null,
      className: '',
    },
    {
      keyCode: 68,
      main: { en: 'd', ru: '' },
      shift: { en: 'D', ru: '' },
      isLetter: true,
      element: null,
      className: '',
    },
    {
      keyCode: 70,
      main: { en: 'f', ru: '' },
      shift: { en: 'F', ru: '' },
      isLetter: true,
      element: null,
      className: '',
    },
    {
      keyCode: 71,
      main: { en: 'g', ru: '' },
      shift: { en: 'G', ru: '' },
      isLetter: true,
      element: null,
      className: '',
    },
    {
      keyCode: 72,
      main: { en: 'h', ru: '' },
      shift: { en: 'H', ru: '' },
      isLetter: true,
      element: null,
      className: '',
    },
    {
      keyCode: 74,
      main: { en: 'j', ru: '' },
      shift: { en: 'J', ru: '' },
      isLetter: true,
      element: null,
      className: '',
    },
    {
      keyCode: 75,
      main: { en: 'k', ru: '' },
      shift: { en: 'K', ru: '' },
      isLetter: true,
      element: null,
      className: '',
    },
    {
      keyCode: 76,
      main: { en: 'l', ru: '' },
      shift: { en: 'L', ru: '' },
      isLetter: true,
      element: null,
      className: '',
    },
    {
      keyCode: 59,
      main: { en: ';', ru: '' },
      shift: { en: ':', ru: '' },
      isLetter: false,
      element: null,
      className: '',
    },
    {
      keyCode: 222,
      main: { en: '\'', ru: '' },
      shift: { en: '"', ru: '' },
      isLetter: false,
      element: null,
      className: '',
    },
    {
      keyCode: 13,
      main: { en: 'Enter', ru: 'Enter' },
      shift: { en: 'Enter', ru: 'Enter' },
      isLetter: false,
      element: null,
      className: 'two-place',
    },
  ],
  [
    {
      keyCode: 16,
      main: { en: 'Shift', ru: 'Shift' },
      shift: { en: 'Shift', ru: 'Shift' },
      isLetter: false,
      element: null,
      className: 'two-place',
    },
    {
      keyCode: 192,
      main: { en: '`', ru: '' },
      shift: { en: '~', ru: '' },
      isLetter: false,
      element: null,
      className: '',
    },
    {
      keyCode: 90,
      main: { en: 'z', ru: '' },
      shift: { en: 'Z', ru: '' },
      isLetter: true,
      element: null,
      className: '',
    },
    {
      keyCode: 88,
      main: { en: 'x', ru: '' },
      shift: { en: 'X', ru: '' },
      isLetter: true,
      element: null,
      className: '',
    },
    {
      keyCode: 67,
      main: { en: 'c', ru: '' },
      shift: { en: 'C', ru: '' },
      isLetter: true,
      element: null,
      className: '',
    },
    {
      keyCode: 86,
      main: { en: 'v', ru: '' },
      shift: { en: 'V', ru: '' },
      isLetter: true,
      element: null,
      className: '',
    },
    {
      keyCode: 66,
      main: { en: 'b', ru: '' },
      shift: { en: 'B', ru: '' },
      isLetter: true,
      element: null,
      className: '',
    },
    {
      keyCode: 78,
      main: { en: 'n', ru: '' },
      shift: { en: 'N', ru: '' },
      isLetter: true,
      element: null,
      className: '',
    },
    {
      keyCode: 77,
      main: { en: 'm', ru: '' },
      shift: { en: 'M', ru: '' },
      isLetter: true,
      element: null,
      className: '',
    },
    {
      keyCode: 188,
      main: { en: ',', ru: '' },
      shift: { en: '<', ru: '' },
      isLetter: false,
      element: null,
      className: '',
    },
    {
      keyCode: 190,
      main: { en: '.', ru: '' },
      shift: { en: '>', ru: '' },
      isLetter: false,
      element: null,
      className: '',
    },
    {
      keyCode: 191,
      main: { en: '/', ru: '' },
      shift: { en: '?', ru: '' },
      isLetter: false,
      element: null,
      className: '',
    },
    {
      keyCode: 16,
      main: { en: 'Shift', ru: 'Shift' },
      shift: { en: 'Shift', ru: 'Shift' },
      isLetter: false,
      element: null,
      className: 'two-place',
    },
  ],
  [
    {
      keyCode: 17,
      main: { en: 'Control', ru: 'Control' },
      shift: { en: 'Control', ru: 'Control' },
      isLetter: false,
      element: null,
      className: '',
      location: 1,
    },
    {
      keyCode: 18,
      main: { en: 'Opt', ru: 'Opt' },
      shift: { en: 'Opt', ru: 'Opt' },
      isLetter: false,
      element: null,
      className: '',
    },
    {
      keyCode: 224,
      main: { en: 'Cmd', ru: 'Cmd' },
      shift: { en: 'Cmd', ru: 'Cmd' },
      isLetter: false,
      element: null,
      className: '',
    },
    {
      keyCode: 32,
      main: { en: 'Space', ru: 'Space' },
      shift: { en: 'Space', ru: 'Space' },
      isLetter: false,
      element: null,
      className: 'five-place',
    },
    {
      keyCode: 224,
      main: { en: 'Cmd', ru: 'Cmd' },
      shift: { en: 'Cmd', ru: 'Cmd' },
      isLetter: false,
      element: null,
      className: '',
    },
    {
      keyCode: 18,
      main: { en: 'Opt', ru: 'Opt' },
      shift: { en: 'Opt', ru: 'Opt' },
      isLetter: false,
      element: null,
      className: '',
    },
  ],
];
